version: 2

run:
  go: '1.23'

linters:
  enable:
    # Security & Correctness
    - staticcheck
    - errcheck
    - gosec
    - govet
    - unused
    - ineffassign
    # Database specific
    - sqlclosecheck
    - rowserrcheck
    # Style & Quality
    - revive
    - gocritic
    - nolintlint
    # Complexity
    - gocyclo
    - funlen
    # HTTP
    - bodyclose
    # Code Standards
    - gochecknoglobals
    # Modernization
    - nilerr
    - unconvert
    - usestdlibvars

formatters:
  enable:
    - gofumpt
    - gci

linters-settings:
  govet:
    enable:
      - shadow
  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
  gocyclo:
    min-complexity: 15
  funlen:
    lines: 80
    statements: 50
  goimports:
    local-prefixes: github.com/ZaparooProject/zaparoo-core
