version: 2

run:
  go: '1.23'

linters:
  enable:
    - staticcheck
    - errcheck
    - gosec
    - govet
    - unused
    - ineffassign
    - sqlclosecheck
    - rowserrcheck
    - revive
    - gocritic
    - nolintlint
    # - gocyclo
    # - funlen
    - bodyclose
    - nilerr
    - unconvert
    - usestdlibvars
    - errorlint
    - exhaustive
    - prealloc
    - noctx
    - nilnil
    - errname
    - wrapcheck
    # - gocognit
    # - cyclop
    # - nestif
    # - maintidx
    - makezero
    - sloglint
    - gosmopolitan
    - depguard
    - tagliatelle
    - testableexamples
    - testifylint
    # - varnamelen
    - decorder
    # - dupl
    - goheader
    - grouper
    - paralleltest
    - tparallel
  settings:
    govet:
      enable:
        - shadow
        - fieldalignment
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
    # gocyclo:
    #   min-complexity: 15
    # funlen:
    #   lines: 80
    #   statements: 50
    goimports:
      local-prefixes: github.com/ZaparooProject/zaparoo-core
    prealloc:
      simple: true
      range-loops: true
      for-loops: true
    revive:
      severity: warning
      rules:
        # - name: argument-limit
          # arguments: [5]
        - name: atomic
        - name: bool-literal-in-expr
        # - name: call-to-gc
        # - name: cognitive-complexity
          # arguments: [15]
        - name: comment-spacings
        - name: confusing-naming
        - name: confusing-results
        - name: constant-logical-expr
        - name: context-as-argument
        - name: context-keys-type
        # - name: cyclomatic
        #   arguments: [15]
        - name: datarace
        # - name: deep-exit
        - name: defer
        - name: dot-imports
        - name: duplicated-imports
        - name: early-return
        - name: empty-block
        - name: empty-lines
        - name: error-naming
        - name: error-return
        - name: error-strings
        - name: errorf
        # - name: flag-parameter
        # - name: function-length
        #   arguments: [50, 0]
        - name: function-result-limit
          arguments: [3]
        - name: get-return
        - name: identical-branches
        - name: if-return
        - name: import-alias-naming
        - name: import-shadowing
        - name: increment-decrement
        - name: indent-error-flow
        - name: line-length-limit
          arguments: [120]
        # - name: max-control-nesting
        #   arguments: [3]
        - name: modifies-parameter
        - name: modifies-value-receiver
        - name: nested-structs
        - name: optimize-operands-order
        - name: range-val-address
        - name: range-val-in-closure
        - name: range
        - name: receiver-naming
        - name: redefines-builtin-id
        - name: redundant-build-tag
        - name: redundant-import-alias
        - name: redundant-test-main-exit
        - name: string-of-int
        - name: struct-tag
          arguments: ["toml,multiline"]
        - name: superfluous-else
        - name: time-date
        - name: time-equal
        - name: time-naming
        - name: unchecked-type-assertion
        - name: unconditional-recursion
        - name: unexported-naming
        - name: unexported-return
        - name: unhandled-error
        - name: unnecessary-format
        - name: unnecessary-stmt
        - name: unreachable-code
        - name: unused-parameter
        - name: unused-receiver
        - name: use-any
        - name: use-errors-new
        - name: use-fmt-print
        - name: useless-break
        - name: var-declaration
        - name: var-naming
        - name: waitgroup-by-value
    # gocognit:
    #   min-complexity: 15
    # cyclop:
    #   max-complexity: 15
    #   skip-tests: true
    # nestif:
    #   min-complexity: 4
    # varnamelen:
    #   min-name-length: 2
    #   ignore-names: ["err", "id", "i", "j", "k", "db", "tx", "ctx", "wg"]
    depguard:
      rules:
        main:
          deny:
            - pkg: "log"
              desc: use zerolog instead
    tagliatelle:
      case:
        rules:
          json: camel
          toml: snake
    # dupl:
    #   threshold: 100
    wrapcheck:
      extra-ignore-sigs:
        - .Err(
    goheader:
      template: |-
        Zaparoo Core
        Copyright (c) {{ YEAR }} The Zaparoo Project Contributors.
        SPDX-License-Identifier: GPL-3.0-or-later

        This file is part of Zaparoo Core.

        Zaparoo Core is free software: you can redistribute it and/or modify
        it under the terms of the GNU General Public License as published by
        the Free Software Foundation, either version 3 of the License, or
        (at your option) any later version.

        Zaparoo Core is distributed in the hope that it will be useful,
        but WITHOUT ANY WARRANTY; without even the implied warranty of
        MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
        GNU General Public License for more details.

        You should have received a copy of the GNU General Public License
        along with Zaparoo Core.  If not, see <http://www.gnu.org/licenses/>.

formatters:
  enable:
    - gofumpt
    - gci
  