// Zaparoo Core
// Copyright (c) 2026 The Zaparoo Project Contributors.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of Zaparoo Core.
//
// Zaparoo Core is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Zaparoo Core is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zaparoo Core.  If not, see <http://www.gnu.org/licenses/>.

// Package credits holds the contributor list and the third-party software
// notices embedded in Core. The data files are generated by
// scripts/credits; regenerate them with "task credits" instead of editing
// them by hand.
package credits

import (
	"bytes"
	"compress/gzip"
	_ "embed"
	"encoding/json"
	"fmt"
	"io"
	"sort"
	"strings"
	"sync"
)

// ComponentsFile and ContributorsFile are the generated data files, relative
// to this package's directory.
const (
	ComponentsFile   = "components.json.gz"
	ContributorsFile = "contributors.json"
)

//go:embed components.json.gz
var componentsData []byte

//go:embed contributors.json
var contributorsData []byte

// LicenseFile is one license, notice or copying file shipped with a
// component. Text is the key of its content in Bundle.Texts, so identical
// files are stored once.
type LicenseFile struct {
	Name string `json:"name"`
	Text string `json:"text"`
}

// Component is one piece of third-party software included in Core.
type Component struct {
	Name    string        `json:"name"`
	Version string        `json:"version,omitempty"`
	URL     string        `json:"url,omitempty"`
	License string        `json:"license"`
	Note    string        `json:"note,omitempty"`
	Files   []LicenseFile `json:"files"`
}

// Bundle is every third-party component with the license texts they use.
type Bundle struct {
	Texts      map[string]string `json:"texts"`
	Components []Component       `json:"components"`
}

// Contributor is a person credited for contributing to Zaparoo Core.
type Contributor struct {
	Name  string `json:"name"`
	Login string `json:"login"`
}

var loadBundle = sync.OnceValues(func() (*Bundle, error) {
	return DecodeBundle(componentsData)
})

// Components returns the embedded third-party software bundle.
func Components() (*Bundle, error) {
	return loadBundle()
}

// Contributors returns the embedded contributor list.
func Contributors() ([]Contributor, error) {
	var contributors []Contributor
	if err := json.Unmarshal(contributorsData, &contributors); err != nil {
		return nil, fmt.Errorf("decoding contributors: %w", err)
	}
	return contributors, nil
}

// EncodeBundle serializes a bundle as indented JSON compressed with gzip. The
// output depends only on the bundle, so regenerating unchanged data gives the
// same bytes.
func EncodeBundle(bundle *Bundle) ([]byte, error) {
	data, err := json.MarshalIndent(bundle, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("encoding credits bundle: %w", err)
	}
	var buf bytes.Buffer
	zw, err := gzip.NewWriterLevel(&buf, gzip.BestCompression)
	if err != nil {
		return nil, fmt.Errorf("compressing credits bundle: %w", err)
	}
	if _, err := zw.Write(append(data, '\n')); err != nil {
		return nil, fmt.Errorf("compressing credits bundle: %w", err)
	}
	if err := zw.Close(); err != nil {
		return nil, fmt.Errorf("compressing credits bundle: %w", err)
	}
	return buf.Bytes(), nil
}

// DecodeBundle reads a bundle written by EncodeBundle.
func DecodeBundle(data []byte) (*Bundle, error) {
	zr, err := gzip.NewReader(bytes.NewReader(data))
	if err != nil {
		return nil, fmt.Errorf("opening credits bundle: %w", err)
	}
	defer func() { _ = zr.Close() }()
	raw, err := io.ReadAll(zr)
	if err != nil {
		return nil, fmt.Errorf("reading credits bundle: %w", err)
	}
	var bundle Bundle
	if err := json.Unmarshal(raw, &bundle); err != nil {
		return nil, fmt.Errorf("decoding credits bundle: %w", err)
	}
	return &bundle, nil
}

// ComponentText renders one component's details and full license texts as
// plain text. format, when not nil, rewrites each license text for display.
func (b *Bundle) ComponentText(component *Component, format func(string) string) string {
	var sb strings.Builder
	writeComponentHeader(&sb, component)
	for _, file := range component.Files {
		text := strings.TrimRight(b.Texts[file.Text], "\n")
		if format != nil {
			text = format(text)
		}
		_, _ = sb.WriteString("\n--- " + file.Name + " ---\n\n")
		_, _ = sb.WriteString(text)
		_, _ = sb.WriteString("\n")
	}
	return sb.String()
}

func writeComponentHeader(sb *strings.Builder, component *Component) {
	_, _ = sb.WriteString(component.Name)
	if component.Version != "" {
		_, _ = sb.WriteString(" " + component.Version)
	}
	_, _ = sb.WriteString("\n")
	if component.URL != "" {
		_, _ = sb.WriteString(component.URL + "\n")
	}
	_, _ = sb.WriteString("License: " + component.License + "\n")
	if component.Note != "" {
		_, _ = sb.WriteString(component.Note + "\n")
	}
}

// Notices renders every component as the plain-text notices file shipped in
// release archives. A license text shared by several components is written
// out in full once and referenced after that.
func (b *Bundle) Notices() string {
	var sb strings.Builder
	_, _ = sb.WriteString("Zaparoo Core third-party software notices\n\n")
	_, _ = sb.WriteString("Zaparoo Core is licensed under the GNU General Public License v3.0 or\n" +
		"later (see LICENSE.txt). It includes the third-party software listed\n" +
		"below, each under its own license. The web app bundled with Zaparoo Core\n" +
		"includes its own third-party notices.\n")

	firstUse := make(map[string]string, len(b.Texts))
	for i := range b.Components {
		component := &b.Components[i]
		_, _ = sb.WriteString("\n" + strings.Repeat("=", 72) + "\n\n")
		writeComponentHeader(&sb, component)
		for _, file := range component.Files {
			_, _ = sb.WriteString("\n--- " + file.Name + " ---\n\n")
			if first, seen := firstUse[file.Text]; seen {
				_, _ = sb.WriteString("Identical to " + first + " above.\n")
				continue
			}
			firstUse[file.Text] = "the " + file.Name + " of " + component.Name
			_, _ = sb.WriteString(strings.TrimRight(b.Texts[file.Text], "\n"))
			_, _ = sb.WriteString("\n")
		}
	}
	return sb.String()
}

// SortComponents orders components by name, ignoring case.
func SortComponents(components []Component) {
	sort.SliceStable(components, func(i, j int) bool {
		return strings.ToLower(components[i].Name) < strings.ToLower(components[j].Name)
	})
}
