package batocera

import (
	"fmt"
	"strings"

	"github.com/ZaparooProject/zaparoo-core/pkg/database/systemdefs"
)

var SystemMap = map[string]string{
	"3do":   systemdefs.System3DO,
	"abuse": systemdefs.SystemDOS,
	// "adam":      systemdefs.SystemColecoAdam,
	"advision":  systemdefs.SystemAdventureVision,
	"amiga1200": systemdefs.SystemAmiga1200,
	"amiga500":  systemdefs.SystemAmiga500,
	"amigacd32": systemdefs.SystemAmigaCD32,
	// "amigacdtv":  systemdefs.SystemAmiga,
	"amstradcpc": systemdefs.SystemAmstrad,
	// "apfm1000":     systemdefs.SystemArcade,
	"apple2": systemdefs.SystemAppleII,
	// "apple2gs": systemdefs.SystemAppleII,
	"arcadia": systemdefs.SystemArcadia,
	"arcade":  systemdefs.SystemArcade,
	// "archimedes":   systemdefs.SystemPC,
	"arduboy": systemdefs.SystemArduboy,
	// "astrocde":     systemdefs.SystemAstrocade,
	"atari2600": systemdefs.SystemAtari2600,
	"atari5200": systemdefs.SystemAtari5200,
	"atari7800": systemdefs.SystemAtari7800,
	"atari800":  systemdefs.SystemAtari800,
	// "atarist":      systemdefs.SystemPC,
	"atom":       systemdefs.SystemAcornAtom,
	"atomiswave": systemdefs.SystemAtomiswave,
	"bbc":        systemdefs.SystemBBCMicro,
	// "c128":         systemdefs.SystemC64,
	//"c20":          systemdefs.SystemVIC20,
	"c64": systemdefs.SystemC64,
	// "camplynx":     systemdefs.SystemLynx48,
	//"cannonball":   systemdefs.SystemArcade,
	"cavestory":    systemdefs.SystemPC,
	"cdi":          systemdefs.SystemCDI,
	"cdogs":        systemdefs.SystemDOS,
	"cgenius":      systemdefs.SystemDOS,
	"channelf":     systemdefs.SystemChannelF,
	"coco":         systemdefs.SystemCoCo2,
	"colecovision": systemdefs.SystemColecoVision,
	// "commanderx16": systemdefs.SystemPC,
	//"corsixth":     systemdefs.SystemPC,
	//"cplus4":       systemdefs.SystemC16,
	"crvision":    systemdefs.SystemCreatiVision,
	"daphne":      systemdefs.SystemDAPHNE,
	"devilutionx": systemdefs.SystemPC,
	"doom3":       systemdefs.SystemPC,
	"dos":         systemdefs.SystemDOS,
	"dreamcast":   systemdefs.SystemDreamcast,
	// "easyrpg":     systemdefs.SystemPC,
	"ecwolf":      systemdefs.SystemDOS,
	"eduke32":     systemdefs.SystemDOS,
	"electron":    systemdefs.SystemAcornElectron,
	"fallout1-ce": systemdefs.SystemWindows,
	"fallout2-ce": systemdefs.SystemWindows,
	"fbneo":       systemdefs.SystemArcade,
	"fds":         systemdefs.SystemFDS,
	// "flash": systemdefs.SystemPC,
	//"fm7":          systemdefs.SystemPC,
	//"fmtowns":      systemdefs.SystemPC,
	"gamate":       systemdefs.SystemGamate,
	"gameandwatch": systemdefs.SystemGameNWatch,
	"gamecom":      systemdefs.SystemGameCom,
	"gamecube":     systemdefs.SystemGameCube,
	"gamegear":     systemdefs.SystemGameGear,
	// "gamepock":     systemdefs.SystemPocketChallengeV2,
	"gb":         systemdefs.SystemGameboy,
	"gb2players": systemdefs.SystemGameboy2P,
	"gba":        systemdefs.SystemGBA,
	"gbc":        systemdefs.SystemGameboyColor,
	// "gbc2players":  systemdefs.SystemGameboy2P,
	//"gmaster":      systemdefs.SystemGameGear,
	//"gp32":         systemdefs.SystemPSP,
	//"gx4000":       systemdefs.SystemAmstrad,
	"gzdoom": systemdefs.SystemDOS,
	// "hcl":          systemdefs.SystemPC,
	"intellivision": systemdefs.SystemIntellivision,
	"jaguar":        systemdefs.SystemJaguar,
	"jaguarcd":      systemdefs.SystemJaguarCD,
	// "laser310":     systemdefs.SystemLaser,
	//"lcdgames":     systemdefs.SystemGameNWatch,
	"lynx":         systemdefs.SystemAtariLynx,
	"macintosh":    systemdefs.SystemMacOS,
	"mame":         systemdefs.SystemArcade,
	"mastersystem": systemdefs.SystemMasterSystem,
	"megadrive":    systemdefs.SystemGenesis,
	"megaduck":     systemdefs.SystemMegaDuck,
	"model3":       systemdefs.SystemModel3,
	"moonlight":    systemdefs.SystemPC,
	"msx1":         systemdefs.SystemMSX,
	// "msx2":      systemdefs.SystemMSX,
	//"msx2+":     systemdefs.SystemMSX,
	//"msxturbor":    systemdefs.SystemMSX,
	"n64": systemdefs.SystemNintendo64,
	// "n64dd":    systemdefs.SystemNintendo64,
	"naomi":    systemdefs.SystemNAOMI,
	"naomi2":   systemdefs.SystemNAOMI2,
	"nds":      systemdefs.SystemNDS,
	"neogeo":   systemdefs.SystemNeoGeo,
	"neogeocd": systemdefs.SystemNeoGeoCD,
	"nes":      systemdefs.SystemNES,
	"ngp":      systemdefs.SystemNeoGeoPocket,
	"ngpc":     systemdefs.SystemNeoGeoPocketColor,
	"o2em":     systemdefs.SystemOdyssey2,
	// "pc88":         systemdefs.SystemPC,
	//"pc98":         systemdefs.SystemPC,
	"pcengine":   systemdefs.SystemTurboGrafx16,
	"pcenginecd": systemdefs.SystemTurboGrafx16CD,
	"pcfx":       systemdefs.SystemPCFX,
	"pdp1":       systemdefs.SystemPDP1,
	"pet":        systemdefs.SystemPET2001,
	// "pico":         systemdefs.SystemGenesis,
	//"pico8":        systemdefs.SystemPC,
	"pokemini":    systemdefs.SystemPokemonMini,
	"psp":         systemdefs.SystemPSP,
	"psx":         systemdefs.SystemPSX,
	"pv1000":      systemdefs.SystemCasioPV1000,
	"samcoupe":    systemdefs.SystemSAMCoupe,
	"satellaview": systemdefs.SystemSNES,
	"saturn":      systemdefs.SystemSaturn,
	"scummvm":     systemdefs.SystemScummVM,
	// "scv":          systemdefs.SystemSG1000,
	"sega32x":     systemdefs.SystemSega32X,
	"segacd":      systemdefs.SystemMegaCD,
	"sg1000":      systemdefs.SystemSG1000,
	"sgb":         systemdefs.SystemSuperGameboy,
	"snes":        systemdefs.SystemSNES,
	"snes-msu1":   systemdefs.SystemSNESMSU1,
	"supergrafx":  systemdefs.SystemSuperGrafx,
	"supervision": systemdefs.SystemSuperVision,
	"ti99":        systemdefs.SystemTI994A,
	// "tutor":        systemdefs.SystemTomyTutor,
	"vc4000":     systemdefs.SystemVC4000,
	"vectrex":    systemdefs.SystemVectrex,
	"virtualboy": systemdefs.SystemVirtualBoy,
	"wii":        systemdefs.SystemWii,
	"wswan":      systemdefs.SystemWonderSwan,
	"wswanc":     systemdefs.SystemWonderSwanColor,
	// "x1":           systemdefs.SystemPC,
	"x68000":     systemdefs.SystemX68000,
	"xegs":       systemdefs.SystemAtariXEGS,
	"zx81":       systemdefs.SystemZX81,
	"zxspectrum": systemdefs.SystemZXSpectrum,
}

func fromBatoceraSystem(batoceraSystem string) (string, error) {
	v, ok := SystemMap[batoceraSystem]
	if !ok {
		return "", fmt.Errorf("unknown system: %s", batoceraSystem)
	}
	return v, nil
}

func toBatoceraSystems(zaparooSystem string) ([]string, error) {
	var results []string
	for k, v := range SystemMap {
		if strings.EqualFold(zaparooSystem, v) {
			results = append(results, k)
		}
	}
	return results, nil
}

var LauncherMap = map[string]string{
	"3do":   "3DO",
	"abuse": "Abuse",
	// "adam":         "Adam",
	"advision":  "AdVision",
	"amiga1200": "Amiga1200",
	"amiga500":  "Amiga500",
	"amigacd32": "AmigaCD32",
	// "amigacdtv":    "AmigaCDTV",
	"amstradcpc": "AmstradCPC",
	// "apfm1000":     "APFM1000",
	"apple2": "Apple2",
	// "apple2gs":     "Apple2GS",
	"arcadia": "Arcadia",
	"arcade":  "Arcade",
	// "archimedes":   "Archimedes",
	"arduboy": "Arduboy",
	// "astrocde":     "Astrocde",
	"atari2600": "Atari2600",
	"atari5200": "Atari5200",
	"atari7800": "Atari7800",
	"atari800":  "Atari800",
	// "atarist":      "AtariST",
	"atom":       "Atom",
	"atomiswave": "Atomiswave",
	"bbc":        "BBC",
	// "c128":         "C128",
	//"c20":          "C20",
	"c64": "C64",
	// "camplynx":     "CampLynx",
	//"cannonball":   "Cannonball",
	"cavestory":    "CaveStory",
	"cdi":          "CDI",
	"cdogs":        "CCogs",
	"cgenius":      "CGenius",
	"channelf":     "Channelf",
	"coco":         "CoCo",
	"colecovision": "ColecoVision",
	// "commanderx16": "CommanderX16",
	//"corsixth":     "CorsixTH",
	//"cplus4":       "CPlus4",
	"crvision":    "CRVision",
	"daphne":      "Daphne",
	"devilutionx": "DevilutionX",
	"doom3":       "Doom3",
	"dos":         "DOS",
	"dreamcast":   "Dreamcast",
	// "easyrpg":      "EasyRPG",
	"ecwolf":      "ECWolf",
	"eduke32":     "ESuke32",
	"electron":    "Electron",
	"fallout1-ce": "Fallout1CE",
	"fallout2-ce": "Fallout2CE",
	"fbneo":       "FBNeo",
	"fds":         "FDS",
	// "flash":        "Flash",
	//"fm7":          "FM7",
	//"fmtowns":      "FMTowns",
	"gamate":       "Gamate",
	"gameandwatch": "GameAndWatch",
	"gamecom":      "GameCom",
	"gamecube":     "GameCube",
	"gamegear":     "GameGear",
	// "gamepock":     "GamePock",
	"gb":         "GB",
	"gb2players": "GB2Players",
	"gba":        "GBA",
	"gbc":        "GBC",
	// "gbc2players":  "GBC2Players",
	//"gmaster":      "GMaster",
	//"gp32":         "GP32",
	//"gx4000":       "GX4000",
	"gzdoom": "GZDoom",
	// "hcl":          "HCL",
	"intellivision": "Intellivision",
	"jaguar":        "Jaguar",
	"jaguarcd":      "JaguarCD",
	// "laser310":     "Laser310",
	//"lcdgames":     "LCDGames",
	"lynx":         "Lynx",
	"macintosh":    "Macintosh",
	"mame":         "MAME",
	"mastersystem": "MasterSystem",
	"megadrive":    "MegaDrive",
	"megaduck":     "MegaDuck",
	"model3":       "Model3",
	"moonlight":    "Moonlight",
	"msx1":         "MSX1",
	// "msx2":         "MSX2",
	//"msx2+":        "MSX2Plus",
	//"msxturbor":    "MSXTurboR",
	"n64": "N64",
	// "n64dd":        "N64DD",
	"naomi":    "NAOMI",
	"naomi2":   "NAOMI2",
	"nds":      "NDS",
	"neogeo":   "NeoGeo",
	"neogeocd": "NeoGeoCD",
	"nes":      "NES",
	"ngp":      "NGP",
	"ngpc":     "NGPC",
	"o2em":     "O2EM",
	// "pc88":         "PC88",
	//"pc98":         "PC98",
	"pcengine":   "PCEngine",
	"pcenginecd": "PCEngineCD",
	"pcfx":       "PCFX",
	"pdp1":       "PDP1",
	"pet":        "PET",
	// "pico":         "Pico",
	//"pico8":        "Pico8",
	"pokemini":    "PokeMini",
	"psp":         "PSP",
	"psx":         "PSX",
	"pv1000":      "PV1000",
	"samcoupe":    "SamCoupe",
	"satellaview": "Satellaview",
	"saturn":      "Saturn",
	"scummvm":     "ScummVM",
	// "scv":          "SCV",
	"sega32x":     "Sega32x",
	"segacd":      "SegaCD",
	"sg1000":      "SG1000",
	"sgb":         "SGB",
	"snes":        "SNES",
	"snes-msu1":   "SNESMSU1",
	"supergrafx":  "SuperGrafx",
	"supervision": "SuperVision",
	"ti99":        "TI99",
	// "tutor":        "Tutor",
	"vc4000":     "VC4000",
	"vectrex":    "Vectrex",
	"virtualboy": "VirtualBoy",
	"wii":        "Wii",
	"wswan":      "WSwan",
	"wswanc":     "WSwanC",
	// "x1":           "X1",
	"x68000":     "X68000",
	"xegs":       "XEGX",
	"zx81":       "ZX81",
	"zxspectrum": "ZXSpectrum",
}
