name: Feature request
description: If you want to have a feature to be added, please fill out this form.
title: "[Feature request]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out this feature form!
  - type: dropdown
    id: platform
    attributes:
      label: Select the platform
      description: On which platform would you like this feature to be added?
      options:
        - MiSTer FPGA
        - Batocera
        - MiSTeX
        - Windows
        - Linux
        - SteamOS
        - Bazzite
        - ChimeraOS
        - LibreELEC/CoreELEC
        - All platforms
      default: 0
    validations:
      required: true
  - type: textarea
    id: feature
    attributes:
      label: Describe the feature
      description: Describe the feature as accurately as possible.
    validations:
      required: true
