name: Question
description: If you have a question, please fill out this form.
title: "[Question]: "
labels: question
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to fill out the question form!
  - type: dropdown
    id: functionality
    attributes:
      label: Select the functionality
      description: What functionality do you have a question about?
      options:
        - GUI
        - Templates
      default: 0
    validations:
      required: true
  - type: textarea
    id: question
    attributes:
      label: Describe your question
      description: Describe your question as accurately as possible.
    validations:
      required: true
  - type: textarea
    id: screenshots
    attributes:
      label: Add screenshots
      description: Please add screenshots if available.
    validations:
      required: false
