#!/bin/bash
APPDIR="$(dirname "$(readlink -f "${0}")")"
export PATH="${APPDIR}/usr/bin:${PATH}"
export LD_LIBRARY_PATH="${APPDIR}/usr/lib:${LD_LIBRARY_PATH}"

if [ $# -eq 0 ]; then
    exec "${APPDIR}/usr/bin/zaparoo" -gui
else
    exec "${APPDIR}/usr/bin/zaparoo" "$@"
fi
