// Zaparoo Core
// Copyright (c) 2026 The Zaparoo Project Contributors.
// SPDX-License-Identifier: GPL-3.0-or-later
//
// This file is part of Zaparoo Core.
//
// Zaparoo Core is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// Zaparoo Core is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with Zaparoo Core.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by TestGenerateStat1Seed (pkg/database/mediascanner); DO NOT EDIT.
// Regenerate with: STAT1_SEED_GEN=1 go test -run TestGenerateStat1Seed ./pkg/database/mediascanner/

package mediadb

// stat1SeedRows are sqlite_stat1 rows captured from a synthetic ~100k-file
// library built through the production staging pipeline. See stat1_seed.go
// for how and when they are applied.
var stat1SeedRows = []struct{ tbl, idx, stat string }{
	{tbl: "DBConfig", idx: "sqlite_autoindex_DBConfig_1", stat: "3 1"},
	{tbl: "Media", idx: "idx_media_browse_sort", stat: "99000 3300 3300 1 1"},
	{tbl: "Media", idx: "idx_media_parentdir", stat: "99000 3300"},
	{tbl: "Media", idx: "idx_media_parentdir_system", stat: "99000 3300 3300"},
	{tbl: "Media", idx: "media_mediatitle_idx", stat: "99000 1"},
	{tbl: "Media", idx: "media_missing_idx", stat: "99000 99000"},
	{tbl: "Media", idx: "media_path_idx", stat: "99000 1"},
	{tbl: "Media", idx: "media_system_path_idx", stat: "99000 3300 1"},
	{tbl: "Media", idx: "media_system_present_path_idx", stat: "99000 3300 1"},
	{tbl: "Media", idx: "media_title_present_idx", stat: "99000 1 1"},
	{tbl: "Media", idx: "sqlite_autoindex_Media_1", stat: "99000 3300 1"},
	{tbl: "MediaTags", idx: "MediaTags", stat: "339075 4 1"},
	{tbl: "MediaTags", idx: "mediatags_tag_media_idx", stat: "339075 28257 1"},
	{tbl: "MediaTitles", idx: "mediatitles_prefilter_idx", stat: "99000 8250 8250"},
	{tbl: "MediaTitles", idx: "mediatitles_secondary_slug_idx", stat: "99000 99000"},
	{tbl: "MediaTitles", idx: "mediatitles_slug_idx", stat: "99000 7"},
	{tbl: "MediaTitles", idx: "mediatitles_system_slug_idx", stat: "99000 3300 1"},
	{tbl: "Systems", idx: "sqlite_autoindex_Systems_1", stat: "30 1"},
	{tbl: "TagTypes", idx: "sqlite_autoindex_TagTypes_1", stat: "49 1"},
	{tbl: "Tags", idx: "tags_tag_idx", stat: "1219 1"},
	{tbl: "Tags", idx: "tags_tagtype_idx", stat: "1219 31"},
	{tbl: "Tags", idx: "tags_type_tag_idx", stat: "1219 31 1"},
	{tbl: "goose_db_version", idx: "", stat: "14"},
}
