version: "3"

tasks:
  build-amd64:
    desc: Build Bazzite AMD64 binary
    cmds:
      - task: :zigcc:build-linux-amd64
        vars:
          PLATFORM: bazzite

  build-arm64:
    desc: Build Bazzite ARM64 binary
    cmds:
      - task: :zigcc:build-linux-arm64
        vars:
          PLATFORM: bazzite