version: "3"

tasks:
  build-amd64:
    desc: Build LibreELEC AMD64 binary
    cmds:
      - task: :zigcc:build-linux-amd64
        vars:
          PLATFORM: libreelec

  build-arm64:
    desc: Build LibreELEC ARM64 binary
    cmds:
      - task: :zigcc:build-linux-arm64
        vars:
          PLATFORM: libreelec

  build-arm:
    desc: Build LibreELEC ARM binary
    cmds:
      - task: :zigcc:build-linux-arm
        vars:
          PLATFORM: libreelec

  deploy:
    cmds:
      - task: build-{{.CLI_ARGS}}
      - scp _build/libreelec_{{.CLI_ARGS}}/zaparoo root@${LIBREELEC_IP}:/storage/zaparoo
      - ssh root@${LIBREELEC_IP} /storage/zaparoo -service restart