version: "3"

tasks:
  build-app:
    desc: Build macOS universal app bundle
    cmds:
      - task: build-arm64
      - task: build-amd64
      - rm -rf "./_build/mac_universal" && mkdir -p "./_build/mac_universal"
      - cp -r "./cmd/mac/app/Zaparoo Core.app" "./_build/mac_universal/Zaparoo Core.app"
      - task: :docker:run
        vars:
          BUILD_OS: darwin
          BUILD_ARCH: arm64
          PLATFORM: mac
          IMAGE_NAME: zaparoo/zigcc
          EXEC: lipo -output ./_build/mac_universal/zaparoo -create ./_build/mac_arm64/zaparoo ./_build/mac_amd64/zaparoo
      - cp ./_build/mac_universal/zaparoo "./_build/mac_universal/Zaparoo Core.app/Contents/MacOS/Zaparoo Core"

  build-arm64:
    desc: Build macOS ARM64 binary
    cmds:
      - task: :zigcc:build-mac-arm64

  build-amd64:
    desc: Build macOS AMD64 binary
    cmds:
      - task: :zigcc:build-mac-amd64

  dev:
    cmds:
      - air --build.cmd "task mac:build-{{.CLI_ARGS}}" --build.bin "./_build/mac_{{.CLI_ARGS}}/zaparoo -daemon"
