version: "3"

tasks:
  build-amd64:
    desc: Build SteamOS AMD64 binary
    cmds:
      - task: :zigcc:build-linux-amd64
        vars:
          PLATFORM: steamos

  deploy-amd64:
    cmds:
      - task: build-amd64
      - scp _build/steamos_amd64/zaparoo deck@${STEAMOS_IP}:/home/deck/zaparoo/zaparoo