version: "3"

tasks:
  build-amd64:
    desc: Build SteamOS AMD64 binary
    cmds:
      - task: :zigcc:build-linux-amd64
        vars:
          PLATFORM: steamos

  deploy:
    cmds:
      - task: build-{{.CLI_ARGS}}
      - scp _build/steamos_{{.CLI_ARGS}}/zaparoo deck@${STEAMOS_IP}:/home/deck/zaparoo/zaparoo