name: Lint

on:
  pull_request:
  push:
    branches:
      - main
    tags:
      - "v*"

jobs:
  lint:
    name: Lint
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'
          
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.3.0
          args: --timeout=5m